# Generated by Django 5.1.1 on 2024-09-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название спектакля')),
                ('slug', models.CharField(max_length=256, verbose_name='Слаг названия')),
                ('short_description', models.TextField()),
                ('is_enable', models.BooleanField(default=True, verbose_name='Показывать в репертуаре')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.CreateModel(
            name='EventShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время начала спектакля')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Показывать в афише')),
                ('is_premiere', models.BooleanField(default=False, verbose_name='Премьера')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Спектакль в афише',
                'verbose_name_plural': 'Спектакли в афише',
            },
        ),
    ]
