# Generated by Django 5.1.1 on 2024-12-04 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import event.models.services.path.event_cover_path
import event.models.services.path.event_program_pdf_path


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventshow',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now,
                                    help_text='Горизонтальное изображение в карточке спектакля',
                                    upload_to=event.models.services.path.event_cover_path.event_cover_path,
                                    verbose_name='Обложка спектакля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность спектакля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='has_intermission',
            field=models.BooleanField(default=False, verbose_name='Есть антракт'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age_limit',
            field=models.IntegerField(default=0, help_text='Минимальный разрешенный возраст зрителя, например, 18 лет',
                                      verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='event',
            name='premiere_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата премьеры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='preview_cover',
            field=models.ImageField(default='', help_text='Обложка спектакля в афише на главной странице',
                                    upload_to=event.models.services.path.event_cover_path.event_cover_path,
                                    verbose_name='Обложка в афише'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='program_pdf',
            field=models.FileField(blank=True, default='', help_text='PDF файл с программой спектакля', null=True,
                                   upload_to=event.models.services.path.event_program_pdf_path.event_program_pdf_path,
                                   verbose_name='Программка спектакля'),
        ),
        migrations.AddField(
            model_name='eventshow',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='event_shows', to='event.event', verbose_name='Спектакль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventshow',
            name='link_to_buy_ticket',
            field=models.CharField(
                default='',
                max_length=256,
                verbose_name='Ссылка на покупку билетов',
                help_text='По этой ссылке пользователь переходит ' +
                          'при клике на кнопку "Купить билет"'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=256, unique=True, verbose_name='Слаг названия'),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=event.models.services.path.event_image_path.event_image_path,
                                            verbose_name='Фото')),
                ('event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event',
                                   verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Фотография спектакля',
                'verbose_name_plural': 'Фотографии спектаклей',
            },
        ),
    ]
