# Generated by Django 5.1.1 on 2024-12-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_eventshow_event_id_event_cover_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dramatist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dramatist', to='people.people', verbose_name='Драматург'),
        ),
        migrations.AddField(
            model_name='event',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to='people.people', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Подробное описание'),
        ),
    ]
