# Generated by Django 5.1.1 on 2025-02-06 11:22

from django.db import migrations, models

import event.models.services.event_cover_path


def forwards_func(apps, schema_editor):
    Event = apps.get_model('event', 'Event')

    for event in Event.objects.all():
        Event.objects.filter(pk=event.pk).update(
            actor_cover=event.cover,
            description_cover=event.cover,
            detail_cover=event.cover
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0005_alter_event_cover_alter_event_preview_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actor_cover',
            field=models.ImageField(
                default='', help_text='Изображение в карточке спектакля',
                upload_to=event.models.services.event_cover_path.event_cover_path,
                verbose_name='Фотография напротив списка действующих лиц спектакля'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_cover',
            field=models.ImageField(
                default='', help_text='Изображение в карточке спектакля',
                upload_to=event.models.services.event_cover_path.event_cover_path,
                verbose_name='Фотография напротив описания спектакля'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='detail_cover',
            field=models.ImageField(
                default='', help_text='Главное изображение в карточке спектакля',
                upload_to=event.models.services.event_cover_path.event_cover_path,
                verbose_name='Обложка спектакля в карточке спектакля'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
