# Generated by Django 5.1.1 on 2025-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_actor_cover_event_description_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
