# Generated by Django 5.1.1 on 2025-02-20 09:12

import django_ckeditor_5.fields
import event.models.services.path.event_cover_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventimage_is_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actor_cover',
            field=models.ImageField(blank=True, help_text='Изображение в карточке спектакля', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Фотография напротив списка действующих лиц спектакля'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, help_text='Изображение в списке спектаклей', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Обложка спектакля'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_cover',
            field=models.ImageField(blank=True, help_text='Изображение в карточке спектакля', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Фотография напротив описания спектакля'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail_cover',
            field=models.ImageField(blank=True, help_text='Главное изображение в карточке спектакля', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Обложка спектакля в карточке спектакля'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, help_text='Формат: чч:мм:сс', null=True, verbose_name='Длительность спектакля'),
        ),
        migrations.AlterField(
            model_name='event',
            name='premiere_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата премьеры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='preview_cover',
            field=models.ImageField(blank=True, help_text='Изображение курсора при наведении на спектакль в афише', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Обложка в афише'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(verbose_name='Краткое описание'),
        ),
    ]
