# Generated by Django 5.1.1 on 2025-02-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_actor_cover_alter_event_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dramatist',
        ),
        migrations.AddField(
            model_name='event',
            name='dramatist',
            field=models.CharField(blank=True, default='', verbose_name='Драматург'),
        ),
    ]
