# Generated by Django 5.1.1 on 2025-04-04 10:27

import event.models.services.path.event_cover_path
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Event = apps.get_model('event', 'Event')

    for event in Event.objects.all():
        Event.objects.filter(pk=event.pk).update(
            cover_in_list=event.cover
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_dramatist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_in_list',
            field=models.ImageField(blank=True, help_text='Изображение в списке спектаклей', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Обложка спектакля в списке спектаклей'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_archival',
            field=models.BooleanField(default=False, help_text='Спектакль архивный, на текущий момент его не ставят', verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_on_main_page',
            field=models.BooleanField(default=True, help_text='При включенном параметре спектакль будет показан на слайдере главной страницы', verbose_name='Показывать на главной странице'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, help_text='Изображение в списке спектаклей в слайдере на главной', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Обложка спектакля на главной'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='При выключенном параметре спектакль будь скрыт на сайте', verbose_name='Показывать на сайте'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
