# Generated by Django 5.1.1 on 2026-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_cover_in_list_event_is_archival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=256, unique=True, verbose_name='Слаг'),
        ),
    ]
