# Generated by Django 5.1.1 on 2026-02-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sort',
            field=models.PositiveIntegerField(default=1000000, help_text='Порядок отображения спектаклей в списке спектаклей (в слайдере) на главной странице', verbose_name='Сортировка'),
        ),
    ]
