# Generated by Django 5.1.1 on 2026-10-02 13:13

import event.models.services.path.event_cover_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_in_list',
            field=models.ImageField(blank=True, help_text='Изображение в списке спектаклей (new-drama.ru/events/)', null=True, upload_to=event.models.services.path.event_cover_path.event_cover_path, verbose_name='Обложка спектакля в списке спектаклей'),
        ),
    ]
