# Generated by Django 5.1.1 on 2024-10-08 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0005_alter_event_premiere_at_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=512, verbose_name='Имя, фамилия')),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='EventPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tag', models.CharField(choices=[('actor', 'Актер'), ('author', 'Автор')], help_text='Раздел в карточке спектакля, в котором будет отображаться участник', max_length=128, verbose_name='Тег')),
                ('role', models.CharField(help_text='Если участник - актер: указать имя персонажа. Если участник выполняет другую роль, например, художник - нужно указать "художник"', max_length=256, verbose_name='Роль участника в спектакле')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Спектакль')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник спектакля',
                'verbose_name_plural': 'Участники спектакля',
            },
        ),
    ]
