# Generated by Django 5.1.1 on 2024-12-04 04:31

import django.db.models.deletion
import people.models.services.photo_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_remove_eventshow_event_id_event_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=512, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=512, verbose_name='Фамилия')),
                ('slug', models.CharField(max_length=256, unique=True, verbose_name='Слаг имени')),
                ('tag', models.CharField(blank=True, choices=[('actor', 'Актер'), ('director', 'Режиссер'), ('author', 'Автор'), ('team', 'Команда')], help_text='Фильтр на странице "Коллектив"', max_length=128, null=True, verbose_name='Тег')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to=people.models.services.photo_path.photo_path, verbose_name='Фотография')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('position', models.CharField(blank=True, default='', max_length=256, verbose_name='Должность')),
                ('education', models.CharField(blank=True, default='', max_length=256, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='EventPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tag', models.CharField(choices=[('actor', 'Актер'), ('author', 'Автор')], help_text='Раздел в карточке спектакля, в котором будет отображаться участник', max_length=128, verbose_name='Тег')),
                ('role', models.CharField(blank=True, default='', help_text='Если участник - актер: указать имя персонажа. Если участник выполняет другую роль, например, художник - нужно указать "художник"', max_length=256, verbose_name='Роль участника в спектакле')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='event.event', verbose_name='Спектакль')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник спектакля',
                'verbose_name_plural': 'Участники спектакля',
            },
        ),
    ]
