# Generated by Django 5.1.1 on 2026-02-18 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpeople',
            name='people',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.people', verbose_name='Участник'),
            preserve_default=False,
        ),
    ]
