/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/event/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить программку спектакля по текущей дате */
        get: operations["event_api_api_get_event_program_by_date"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-shows/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список спектаклей в афише c текущего месяца */
        get: operations["event_api_event_shows_api_get_event_shows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех спектаклей: репертуар */
        get: operations["event_api_events_api_get_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить данные спектакля по slug */
        get: operations["event_api_events_api_get_event_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список людей театра */
        get: operations["people_api_get_people_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить данные человека по slug */
        get: operations["people_api_get_people_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/info-blocks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список инфо-блоков */
        get: operations["info_api_info_blocks_api_get_info_block_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список отзывов */
        get: operations["info_api_reviews_api_get_review_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/popups/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить активный поп-ап на текущий момент времени */
        get: operations["info_api_popups_api_get_active_popup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/partners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список партнеров */
        get: operations["info_api_partners_api_get_partner_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventShowFilterSchema */
        EventShowFilterSchema: {
            /** Event Id */
            event_id?: number | null;
        };
        /** EventInEventShowSchema */
        EventInEventShowSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Short Description */
            short_description: string;
            /** Preview Cover */
            preview_cover?: string | null;
            /** Min Age Limit */
            min_age_limit: number;
        };
        /** EventShowOutSchema */
        EventShowOutSchema: {
            /** Id */
            id: number;
            event: components["schemas"]["EventInEventShowSchema"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Is Premiere */
            is_premiere: boolean;
            /** Link To Buy Ticket */
            link_to_buy_ticket: string;
            /** Day Of Week */
            day_of_week: string;
        };
        /** EventFilterSchema */
        EventFilterSchema: {
            /**
             * Show On Main Page
             * @description Показывать на главной странице
             */
            show_on_main_page?: boolean;
            /**
             * Order By
             * @description Сортировка
             * @enum {string}
             */
            order_by?: "?" | "name" | "sort";
        };
        /** EventPreviewSchema */
        EventPreviewSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Dramatist */
            dramatist: string;
            /** Short Description */
            short_description: string;
            /** Cover */
            cover: string;
            /** Preview Cover */
            preview_cover?: string | null;
            /** Min Age Limit */
            min_age_limit: number;
            /** Is Archival */
            is_archival: boolean;
            /** Cover In List */
            cover_in_list?: string | null;
            producer?: components["schemas"]["PeopleInEventOutSchema"] | null;
            /** Cover Compressed Url */
            cover_compressed_url: string;
        };
        /** PeopleInEventOutSchema */
        PeopleInEventOutSchema: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** EventDetailResponseSchema */
        EventDetailResponseSchema: {
            event: components["schemas"]["EventDetailSchema"];
            /** Peoples */
            peoples: components["schemas"]["EventPeopleInEventOutSchema"][];
            /** Images */
            images: components["schemas"]["EventImageOutSchema"][];
        };
        /** EventDetailSchema */
        EventDetailSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Short Description */
            short_description: string;
            /** Min Age Limit */
            min_age_limit: number;
            /** Description */
            description: string;
            /** Has Intermission */
            has_intermission: boolean;
            /** Premiere At */
            premiere_at?: string | null;
            /** Dramatist */
            dramatist: string;
            /** Duration Format */
            duration_format: string;
            /** Cover Compressed Url */
            cover_compressed_url?: string | null;
            /** Detail Cover Compressed Url */
            detail_cover_compressed_url?: string | null;
            /** Description Cover Compressed Url */
            description_cover_compressed_url?: string | null;
            /** Actor Cover Compressed Url */
            actor_cover_compressed_url?: string | null;
            producer?: components["schemas"]["PeopleInEventOutSchema"] | null;
        };
        /** EventImageOutSchema */
        EventImageOutSchema: {
            /** Id */
            id: number;
            /** Image */
            image: string;
            /** Image Compressed Url */
            image_compressed_url?: string | null;
        };
        /** EventPeopleInEventOutSchema */
        EventPeopleInEventOutSchema: {
            /** Id */
            id: number;
            /** Tag */
            tag?: string | null;
            /** Role */
            role?: string | null;
            people: components["schemas"]["PeopleInEventOutSchema"];
        };
        /** PeoplePreviewSchema */
        PeoplePreviewSchema: {
            /** ID */
            id?: number | null;
            /** Имя */
            first_name: string;
            /** Фамилия */
            last_name: string;
            /** Слаг имени */
            slug: string;
            /**
             * Тег
             * @description Фильтр на странице "Коллектив"
             */
            tag?: string | null;
            /**
             * Фотография
             * @default
             */
            photo: string | null;
        };
        /** PeopleDetailSchema */
        PeopleDetailSchema: {
            /** ID */
            id?: number | null;
            /** Имя */
            first_name: string;
            /** Фамилия */
            last_name: string;
            /** Слаг имени */
            slug: string;
            /**
             * Тег
             * @description Фильтр на странице "Коллектив"
             */
            tag?: string | null;
            /**
             * Фотография
             * @default
             */
            photo: string | null;
            /**
             * Описание
             * @default
             */
            description: string | null;
            /** Дата рождения */
            birthday?: string | null;
            /**
             * Должность
             * @default
             */
            position: string | null;
            /**
             * Образование
             * @default
             */
            education: string | null;
        };
        /** InfoBlockFilterSchema */
        InfoBlockFilterSchema: {
            /** In Menu */
            in_menu?: boolean | null;
        };
        /** InfoBlockOutSchema */
        InfoBlockOutSchema: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Btn Text */
            btn_text: string;
            /** Btn Link */
            btn_link: string;
            /** Cover Compressed Url */
            cover_compressed_url: string;
            /** Menu Title Slug */
            menu_title_slug: string;
            /** Menu Title */
            menu_title: string;
        };
        /** ReviewFilterSchema */
        ReviewFilterSchema: {
            /** Is Enable Main */
            is_enable_main?: boolean | null;
            /** Is Enable Event */
            is_enable_event?: boolean | null;
            /** Event Id */
            event_id?: number | null;
        };
        /** ReviewOutSchema */
        ReviewOutSchema: {
            /** Id */
            id: number;
            /** Image */
            image: string;
            /** Image Compressed Url */
            image_compressed_url: string;
            /** Nickname */
            nickname?: string | null;
        };
        /** PopupOutSchema */
        PopupOutSchema: {
            /** Id */
            id: number;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
            /** Short Title */
            short_title: string;
            /** Content */
            content: string;
            /** Btn Text */
            btn_text: string;
            /** Btn Link */
            btn_link: string;
            /** Cover */
            cover: string;
            /** Cover Compressed Url */
            cover_compressed_url: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
        };
        /** PartnerOutSchema */
        PartnerOutSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Logo */
            logo: string;
            /** Link */
            link: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    event_api_api_get_event_program_by_date: {
        parameters: {
            query?: {
                event_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    event_api_event_shows_api_get_event_shows: {
        parameters: {
            query?: {
                event_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventShowOutSchema"][];
                };
            };
        };
    };
    event_api_events_api_get_events: {
        parameters: {
            query?: {
                /** @description Показывать на главной странице */
                show_on_main_page?: boolean;
                /** @description Сортировка */
                order_by?: "?" | "name" | "sort";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPreviewSchema"][];
                };
            };
        };
    };
    event_api_events_api_get_event_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponseSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    people_api_get_people_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePreviewSchema"][];
                };
            };
        };
    };
    people_api_get_people_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleDetailSchema"];
                };
            };
        };
    };
    info_api_info_blocks_api_get_info_block_list: {
        parameters: {
            query?: {
                in_menu?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoBlockOutSchema"][];
                };
            };
        };
    };
    info_api_reviews_api_get_review_list: {
        parameters: {
            query?: {
                is_enable_main?: boolean | null;
                is_enable_event?: boolean | null;
                event_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOutSchema"][];
                };
            };
        };
    };
    info_api_popups_api_get_active_popup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopupOutSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    info_api_partners_api_get_partner_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOutSchema"][];
                };
            };
        };
    };
}
