/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/event/event_show/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список спектаклей в афише c текущего месяца */
        get: operations["event_api_get_event_show_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить программку спектакля по текущей дате */
        get: operations["event_api_get_event_program_by_date"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event/event/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех спектаклей: репертуар */
        get: operations["event_api_get_event_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event/event/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить данные спектакля по slug */
        get: operations["event_api_get_event_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список людей театра */
        get: operations["people_api_get_people_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить данные человека по slug */
        get: operations["people_api_get_people_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/info-blocks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список инфо-блоков */
        get: operations["info_api_info_blocks_api_get_info_block_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список отзывов */
        get: operations["info_api_reviews_api_get_review_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/popups/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить активный поп-ап на текущий момент времени */
        get: operations["info_api_popups_api_get_active_popup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/partners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список партнеров */
        get: operations["info_api_partners_api_get_partner_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventPreviewSchema */
        EventPreviewSchema: {
            producer: components["schemas"]["PeoplePreviewSchema"] | null;
            /** ID */
            id?: number | null;
            /** Название спектакля */
            name: string;
            /** Слаг */
            slug: string;
            /**
             * Драматург
             * @default
             */
            dramatist: string | null;
            /** Краткое описание */
            short_description: string;
            /**
             * Обложка спектакля на главной
             * @description Изображение в списке спектаклей в слайдере на главной
             */
            cover?: string | null;
            /**
             * Обложка в афише
             * @description Изображение курсора при наведении на спектакль в афише
             */
            preview_cover?: string | null;
            /**
             * Возрастное ограничение
             * @description Минимальный разрешенный возраст зрителя, например, 18 лет
             * @default 0
             */
            min_age_limit: number;
            /**
             * Архив
             * @description Спектакль архивный, на текущий момент его не ставят
             * @default false
             */
            is_archival: boolean;
            /**
             * Обложка спектакля в списке спектаклей
             * @description Изображение в списке спектаклей
             */
            cover_in_list?: string | null;
        };
        /** EventShowOutSchema */
        EventShowOutSchema: {
            /** Id */
            id: number;
            event: components["schemas"]["EventPreviewSchema"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Is Premiere */
            is_premiere: boolean;
            /** Link To Buy Ticket */
            link_to_buy_ticket: string;
            /** Day Of Week */
            day_of_week: string;
        };
        /** PeoplePreviewSchema */
        PeoplePreviewSchema: {
            /** ID */
            id?: number | null;
            /** Имя */
            first_name: string;
            /** Фамилия */
            last_name: string;
            /** Слаг имени */
            slug: string;
            /**
             * Тег
             * @description Фильтр на странице "Коллектив"
             */
            tag?: string | null;
            /**
             * Фотография
             * @default
             */
            photo: string | null;
        };
        /** EventDetailSchema */
        EventDetailSchema: {
            /** Peoples */
            peoples: components["schemas"]["EventPeopleOutSchema"][];
            /** Images */
            images: components["schemas"]["EventImageOutSchema"][];
            producer: components["schemas"]["PeopleShortSchema"] | null;
            /** Duration Format */
            duration_format: string | null;
            /** Cover Compressed Url */
            cover_compressed_url?: string | null;
            /** Detail Cover Compressed Url */
            detail_cover_compressed_url?: string | null;
            /** Description Cover Compressed Url */
            description_cover_compressed_url?: string | null;
            /** Actor Cover Compressed Url */
            actor_cover_compressed_url?: string | null;
            /** ID */
            id?: number | null;
            /** Название спектакля */
            name: string;
            /** Слаг */
            slug: string;
            /** Краткое описание */
            short_description: string;
            /**
             * Возрастное ограничение
             * @description Минимальный разрешенный возраст зрителя, например, 18 лет
             * @default 0
             */
            min_age_limit: number;
            /**
             * Подробное описание
             * @default
             */
            description: string | null;
            /**
             * Есть антракт
             * @default false
             */
            has_intermission: boolean;
            /** Дата премьеры */
            premiere_at?: string | null;
            /**
             * Драматург
             * @default
             */
            dramatist: string | null;
            /**
             * Обложка спектакля на главной
             * @description Изображение в списке спектаклей в слайдере на главной
             */
            cover?: string | null;
            /**
             * Обложка спектакля в списке спектаклей
             * @description Изображение в списке спектаклей
             */
            cover_in_list?: string | null;
            /**
             * Обложка в афише
             * @description Изображение курсора при наведении на спектакль в афише
             */
            preview_cover?: string | null;
            /**
             * Обложка спектакля в карточке спектакля
             * @description Главное изображение в карточке спектакля
             */
            detail_cover?: string | null;
            /**
             * Фотография напротив описания спектакля
             * @description Изображение в карточке спектакля
             */
            description_cover?: string | null;
            /**
             * Фотография напротив списка действующих лиц спектакля
             * @description Изображение в карточке спектакля
             */
            actor_cover?: string | null;
            /**
             * Архив
             * @description Спектакль архивный, на текущий момент его не ставят
             * @default false
             */
            is_archival: boolean;
        };
        /** EventImageOutSchema */
        EventImageOutSchema: {
            /** Image Compressed Url */
            image_compressed_url?: string | null;
            /** ID */
            id?: number | null;
            /** Фото */
            image: string;
        };
        /** EventPeopleOutSchema */
        EventPeopleOutSchema: {
            people: components["schemas"]["PeopleShortSchema"];
            /** ID */
            id?: number | null;
            /**
             * Тег
             * @description Раздел в карточке спектакля, в котором будет отображаться участник
             */
            tag: string;
            /**
             * Роль участника в спектакле
             * @description Если участник - актер: указать имя персонажа. Если участник выполняет другую роль, например, художник - нужно указать "художник"
             * @default
             */
            role: string | null;
            /**
             * Сортировка
             * @default 0
             */
            sort: number;
        };
        /** PeopleShortSchema */
        PeopleShortSchema: {
            /** ID */
            id?: number | null;
            /** Имя */
            first_name: string;
            /** Фамилия */
            last_name: string;
        };
        /** PeopleDetailSchema */
        PeopleDetailSchema: {
            /** ID */
            id?: number | null;
            /** Имя */
            first_name: string;
            /** Фамилия */
            last_name: string;
            /** Слаг имени */
            slug: string;
            /**
             * Тег
             * @description Фильтр на странице "Коллектив"
             */
            tag?: string | null;
            /**
             * Фотография
             * @default
             */
            photo: string | null;
            /**
             * Описание
             * @default
             */
            description: string | null;
            /** Дата рождения */
            birthday?: string | null;
            /**
             * Должность
             * @default
             */
            position: string | null;
            /**
             * Образование
             * @default
             */
            education: string | null;
        };
        /** InfoBlockFilterSchema */
        InfoBlockFilterSchema: {
            /** In Menu */
            in_menu?: boolean | null;
        };
        /** InfoBlockOutSchema */
        InfoBlockOutSchema: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Btn Text */
            btn_text: string;
            /** Btn Link */
            btn_link: string;
            /** Cover */
            cover: string;
            /** Menu Title Slug */
            menu_title_slug: string;
            /** Menu Title */
            menu_title: string;
        };
        /** ReviewFilterSchema */
        ReviewFilterSchema: {
            /** Is Enable Main */
            is_enable_main?: boolean | null;
            /** Is Enable Event */
            is_enable_event?: boolean | null;
            /** Event Id */
            event_id?: number | null;
        };
        /** ReviewOutSchema */
        ReviewOutSchema: {
            /** Id */
            id: number;
            /** Image */
            image: string;
            /** Nickname */
            nickname?: string | null;
        };
        /** PopupOutSchema */
        PopupOutSchema: {
            /** Id */
            id: number;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
            /** Short Title */
            short_title: string;
            /** Content */
            content: string;
            /** Btn Text */
            btn_text: string;
            /** Btn Link */
            btn_link: string;
            /** Cover */
            cover: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
        };
        /** PartnerOutSchema */
        PartnerOutSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Logo */
            logo: string;
            /** Link */
            link: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    event_api_get_event_show_list: {
        parameters: {
            query?: {
                event_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventShowOutSchema"][];
                };
            };
        };
    };
    event_api_get_event_program_by_date: {
        parameters: {
            query?: {
                event_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    event_api_get_event_list: {
        parameters: {
            query?: {
                show_on_main_page?: boolean;
                order_by?: "?" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPreviewSchema"][];
                };
            };
        };
    };
    event_api_get_event_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailSchema"];
                };
            };
        };
    };
    people_api_get_people_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePreviewSchema"][];
                };
            };
        };
    };
    people_api_get_people_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleDetailSchema"];
                };
            };
        };
    };
    info_api_info_blocks_api_get_info_block_list: {
        parameters: {
            query?: {
                in_menu?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoBlockOutSchema"][];
                };
            };
        };
    };
    info_api_reviews_api_get_review_list: {
        parameters: {
            query?: {
                is_enable_main?: boolean | null;
                is_enable_event?: boolean | null;
                event_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOutSchema"][];
                };
            };
        };
    };
    info_api_popups_api_get_active_popup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopupOutSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    info_api_partners_api_get_partner_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOutSchema"][];
                };
            };
        };
    };
}
