# Generated by Django 5.1.1 on 2024-12-25 05:01

import info.models.services.info_block_cover_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('btn_text', models.CharField(help_text='Текст будет отображаться внутри кнопки. Примеры: "написать в telegram", "перейти на сайт"', max_length=256, verbose_name='Текст кнопки действия')),
                ('btn_link', models.CharField(help_text='Ресурс, на который будет перенаправлен пользователь при клике по кнопке', max_length=512, verbose_name='Ссылка кнопки')),
                ('cover', models.ImageField(help_text='Картинка инфо-блока', upload_to=info.models.services.info_block_cover_path.info_block_cover_path, verbose_name='Обложка')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Инфо-блок',
                'verbose_name_plural': 'Инфо-блоки',
            },
        ),
    ]
