# Generated by Django 5.1.1 on 2025-01-09 11:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_infoblock_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblock',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
