# Generated by Django 5.1.1 on 2025-01-22 09:19
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0003_alter_infoblock_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Изображение на главной', upload_to='viewer_image/',
                                            verbose_name='Фотография')),
                ('nickname',
                 models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Никнейм')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort',
                 models.IntegerField(default=0, help_text='Порядок отображения на сайте (от меньшего к большему)',
                                     verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Зритель',
                'verbose_name_plural': 'Зрители',
            },
        ),
    ]
