# Generated by Django 5.1.1 on 2025-01-24 03:43

import info.models.partner_model
import info.models.services.partner_logo_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('logo', models.FileField(help_text='Логотип компании на главной', upload_to=info.models.services.partner_logo_path.partner_logo_path, validators=[info.models.partner_model.validate_svg], verbose_name='Логотип')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort', models.IntegerField(default=0, help_text='Порядок отображения на сайте (от меньшего к большему)', verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
