# Generated by Django 5.1.1 on 2025-01-28 05:06

from django.db import migrations, models
from slugify import slugify


def forwards_func(apps, schema_editor):
    InfoBlock = apps.get_model('info', 'InfoBlock')

    for block in InfoBlock.objects.all():
        menu_title = block.title
        menu_title_slug = slugify(block.title)

        InfoBlock.objects.filter(pk=block.pk).update(
            menu_title=menu_title,
            menu_title_slug=menu_title_slug
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('info', '0005_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblock',
            name='title',
            field=models.CharField(max_length=512, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='infoblock',
            name='in_menu',
            field=models.BooleanField(
                default=False,
                help_text='Добавляет якорную ссылку в меню (хедер)',
                verbose_name='Добавить пункт в меню'
            ),
        ),
        migrations.AddField(
            model_name='infoblock',
            name='menu_title',
            field=models.CharField(
                default='',
                help_text='Текст якорной ссылки, который будет отображаться в меню (хедере)',
                max_length=256,
                verbose_name='Заголовок в меню'
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='infoblock',
            name='menu_title_slug',
            field=models.CharField(
                default='',
                max_length=256,
                unique=False,
                verbose_name='Якорная ссылка'
            ),
            preserve_default=False,
        ),

        migrations.RunPython(forwards_func, reverse_func),

        migrations.AlterField(
            model_name='infoblock',
            name='menu_title_slug',
            field=models.CharField(
                max_length=256,
                unique=True,
                verbose_name='Якорная ссылка'
            ),
            preserve_default=False,
        ),
    ]
