# Generated by Django 5.1.1 on 2025-02-10 05:04

import django.db.models.deletion
import info.models.services.review_image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_actor_cover_event_description_cover_and_more'),
        ('info', '0006_infoblock_in_menu_infoblock_menu_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Фото/скрин отзыва', upload_to=info.models.services.review_image_path.review_image_path, verbose_name='Фотография')),
                ('nickname', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Никнейм')),
                ('is_enable_main', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('is_enable_event', models.BooleanField(default=False, verbose_name='Показывать в карточке спектакля')),
                ('sort', models.IntegerField(default=0, help_text='Порядок отображения на сайте (от меньшего к большему)', verbose_name='Сортировка')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reviews', to='event.event', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
