# Generated by Django 5.1.1 on 2025-02-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_review_delete_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(default='', help_text='По этой ссылке пользователь переходит при клике на логотип партнера', max_length=256, verbose_name='Ссылка на сайт партнера'),
        ),
    ]
