# Generated by Django 5.1.1 on 2025-03-20 07:15

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_partner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('btn_text', models.CharField(help_text='Текст будет отображаться внутри кнопки. Примеры: "Купить билет", "Перейти на сайт"', max_length=256, verbose_name='Текст кнопки действия')),
                ('btn_link', models.CharField(help_text='Ресурс, на который будет перенаправлен пользователь при клике по кнопке', max_length=512, verbose_name='Ссылка кнопки')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время начала показа')),
                ('end_at', models.DateTimeField(verbose_name='Дата и время окончания показа')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Поп-ап',
                'verbose_name_plural': 'Поп-апы',
            },
        ),
    ]
