# Generated by Django 5.1.1 on 2026-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='is_show_timer',
            field=models.BooleanField(default=True, help_text='Таймер будет отображаться в поп-апе. Если выключено, то таймер будет скрыт.', verbose_name='Показывать таймер оставшегося времени'),
        ),
    ]
